### ISSUE TITLE
Beautify webpage string literal

### ISSUE THREAD

**Issue by willprice** [jda0/hedgehog-clock#3]
https://github.com/jda0/hedgehog-clock/blob/694d76ac03cb518dfe464def2efdad7efd8add9b/src/hh_server.cpp#L6

Oh dear god, my eyes, my poor eyes.

You know you can have adjacent strings separated by spaces and they'll be combined:

```
"hello" " " "world" "!"
```

is the same as

```
"hello world!"
```

**Comment by jda0** [comment]
Have you seen https://github.com/MVSE-Outreach/arduino-hedgehog-bot/blob/gh-pages/challenges/bot/challenge1.html recently? 😜

**Comment by willprice** [comment]
That's how I like formatting, I know how far through a file I am by how many leading tabs there is XD lol that is a mess.

**Comment by jda0** [comment]
Somewhat improved in latest commit - styles still on one line, most of script still on one line, still minimised in unpretty ways - but somewhat improved.
